### ISSUE TITLE
What's different between quick-format-unescaped and quick-format

### ISSUE THREAD

**Issue by fengmk2** [davidmarkclements/quick-format#10]
- https://www.npmjs.com/package/quick-format-unescaped
- https://www.npmjs.com/package/quick-format

They're using the same git repo https://github.com/davidmarkclements/quick-format.

**Comment by mcollina** [comment]
This is quick-format-unescaped: https://github.com/davidmarkclements/quick-format/tree/unescaped.

**Comment by davidmarkclements** [comment]
@fengmk2 the point of quick-format-unescaped is for situations where you want to interpolate without escaping (because escaping will happen at some higher point) 

this prevents double escaping - rolling it as a separate module (rather than using an option) was necessary because the option check would have caused performance degradation  - we're at the maximum amount of logical paths (e.g. conditional checks) before V8 will bail on inlining the function
